name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    name: Build and Upload
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: docker-dns
            asset_name: docker-dns-linux-x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: docker-dns
            asset_name: docker-dns-linux-x86_64-musl
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: docker-dns
            asset_name: docker-dns-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: docker-dns
            asset_name: docker-dns-macos-aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: docker-dns.exe
            asset_name: docker-dns-windows-x86_64.exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}

      - name: Install musl-tools (Linux musl only)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }} --verbose

      - name: Strip binary (Linux and macOS)
        if: matrix.os != 'windows-latest'
        run: strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

      - name: Rename binary for upload
        run: |
          mkdir -p release-assets
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} release-assets/${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: release-assets/${{ matrix.asset_name }}
